package(default_visibility = ["//visibility:public"])

load("//python:versions.bzl", "multipython_gen_toolchains")

multipython_gen_toolchains(
    toolchains = [
        "python3_9",
        "python3_10",
    ],
)
